export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';
export const UPDATE_SUBSCRIPTION = 'UPDATE_SUBSCRIPTION';
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
export const SET_THEME = 'SET_THEME';